//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DP_Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPOINTMENT_DETAILS
    {
        public int ID { get; set; }
        public Nullable<int> APPOINTMENT_ID { get; set; }
        public int APPOINTMENT_STARTTIME { get; set; }
        public int APPOINTMENT_ENDTIME { get; set; }
        public string DISEASE_DETAILS { get; set; }
    
        public virtual APPOINTMENT APPOINTMENT { get; set; }
    }
}
