//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DP_Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR_SPEC
    {
        public int ID { get; set; }
        public Nullable<int> DOCTOR_ID { get; set; }
        public string DOCTOR_SPEC1 { get; set; }
        public string DOCTOR_ADDRESS { get; set; }
        public string DOCTOR_MCODE { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
