//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DP_Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLOT
    {
        public int ID { get; set; }
        public Nullable<int> START_TIME { get; set; }
        public Nullable<int> END_TIME { get; set; }
    }
}
